name: gruchang_thai_gold_smith
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3
  pull_to_refresh: ^2.0.0
  loader_overlay: ^2.1.0
  loading_animation_widget: ^1.2.0+4
  responsive_framework: ^0.2.0
  logger: ^1.3.0
  catcher: ^0.7.0
  firebase_core: ^2.8.0
  package_info_plus: ^3.0.3
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  fonts:
    - family: Cloud
      fonts:
        - asset: assets/fonts/cloud/Cloud-Light.otf
        - asset: assets/fonts/cloud/Cloud-Bold.otf
          weight: 500
    - family: Khanok
      fonts:
        - asset: assets/fonts/khanok/SOV_JD_KraNok.ttf
    - family: Chofa
      fonts:
        - asset: assets/fonts/chofa/KRRChofaDemo-Demo.otf
    - family: Sathaporn
      fonts:
        - asset: assets/fonts/sathaporn/KJR_SATHAPORN_TODLONG.ttf
    - family: Thaispirit
      fonts:
        - asset: assets/fonts/thaispirit/KRR-THAISPIRIT.ttf

  assets:
    - assets/images/
    - assets/langs/